name: dockerize flask application
on: push
jobs:
  build-container:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build docker image
        run: docker build . -t python-code:${{ github.run_number }}
      - name: Push to docker hub
        run: docker push -t sumedhajagtap/docker-container python-code:${{ github.run_number }}

      # - name: Publish to Docker hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: sumedhajagtap/docker-container
      #     tags: latest, ${{ github.run_number }}

