name: dockerize flask application
on: push
jobs:
  build-container:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # - name: Publish to Docker hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: sumedhajagtap/docker-container
      #     tags: latest, ${{ github.run_number }}

